### ISSUE TITLE
Backend - Unique Snack

### ISSUE THREAD

**Issue by wh1pch81n** [wh1pch81n/RateMySnack#11]
Each Snack should be unique.  If a submit() request is made, verify that there is no duplicates.  If there are no duplicates then submit it to the server.  If it already exists, then the request should be denied.

If denied, send the completion block an NSError object with the correct error code
Error codes specified in #24

**Comment by wh1pch81n** [comment]
@Iceyhan  I made some changes to this issue.  Now it only specifies the need for duplication detection.

**Comment by Iceyhan** [comment]
testing

**Comment by Iceyhan** [comment]
hello?

**Comment by wh1pch81n** [comment]
Hi there.  This is the Issue.  But you should actually be making this discussion on the branch you just committed instead
