### ISSUE TITLE
5 star rating UI

### ISSUE THREAD

**Issue by wh1pch81n** [wh1pch81n/RateMySnack#7]
### Brief

Create a UI (User Interface) that will give users the ability to Rate something on a scale of 1 to 5 stars.  
###### Class Name
- Create a UIView subclass called RMSStarRateView.
###### Star States
- The view should show a horizontal array of 5 stars.  
- When No stars have been selected all 5 stars should be in a reactive state.
- When User clicks the left most star it is considered a star rating of 1
- When User clicks the 2nd to the left star it is considered a star rating of 2
- When User clicks the 3rd to the left star it is considered a star rating of 3
- When User clicks the 4th to the left star it is considered a star rating of 4
- When User clicks the 5th to the left star it is considered a star rating of 5
###### User Interaction
- The RMSStarRateView will be selectable.  Depending on where they press, will determine which stars get highlighted and which gets deselected.

**Comment by jessnev4life** [comment]
still working on it
